api/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.urls import re_path
from rest_framework.urlpatterns import format_suffix_patterns

from api import views

urlpatterns = [
    re_path(r'^$', views.WelcomeView.as_view()),
    re_path(r'^health/$', views.Health.as_view(), name='health'),
    re_path(r'^csv_upload/$', views.CsvUploadView.as_view(), name='csv_upload'),
    re_path(r'^services/$', views.ServiceList.as_view(), name='service_list'),
    re_path(r'^services/(?P<uuid>[^/]+)/$',
        views.ServiceDetail.as_view(), name='service_detail'),
    re_path(r'^res/$', views.ResourceList.as_view(), name='resource_list'),
    re_path(r'^res/(?P<uuid>[^/]+)/$',
        views.ResourceDetail.as_view(), name='resource_detail'),
    re_path(r'^res/(?P<uuid>[^/]+)/attributes/$',
        views.ResourceAttributes.as_view(), name='resource_attributes')
]

urlpatterns = format_suffix_patterns(urlpatterns)
app_name = 'api'

usergui/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.urls import re_path
from usergui import views

urlpatterns = [
    re_path('^$', views.index, name='index'),
    re_path('^detail/(?P<uuid>[^/]+)/$', views.detail, name="detail"),
]
app_name = 'usergui'

usergui/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.

usergui/views.py
from django.shortcuts import render, get_object_or_404

from api.models import Resource

# Create your views here.

def index(request):
    resources = Resource.objects.filter(eppn=request.eppn).order_by("sp__name",)
    return render(request, "usergui/index.html", {'resources': resources})

def detail(request, uuid):
    resource = get_object_or_404(Resource, eppn=request.eppn, uuid=uuid)
    return render(request, "usergui/detail.html", {'resource': resource})

usergui/templates/usergui/base.html
{% extends "admin/base.html" %}

usergui/templates/usergui/detail.html
{% extends "usergui/base.html" %}

{% block content %}
<table>
  <tr>
    <th>Gültig bis:</th>
    <td>{{ resource.expiry_date }}</td>
  </tr>
  <tr>
    <th>Löschdatum:</th>
    <td>{{ resource.deletion_date }}</td>
  </tr>
  <tr>
    <th>Serviceprovider:</th>
    <td>{{ resource.sp.name }}</td>
  </tr>
  {% for attr in resource.attribute_set %}
  <tr>
    <th>{{ attr.name }}</th>
    <td>{{ attr.value }}</td>
  </tr>
  {% endfor %}
</table>
{% endblock %}

usergui/templates/usergui/index.html
{% extends "usergui/base.html" %}

{% block content %}
<ul>
{% for resource in resources %}
<li><a href="{% url "usergui:detail" uuid=resource.uuid %}">{{resource}}</a></li>
{% endfor %}
</ul>
{% endblock %}